version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - estadia_ja_network

  db-test:
    image: postgres:15
    container_name: postgres_db_test
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: estadia_test_db
    ports:
      - '5434:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - estadia_ja_network

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    ports:
      - '8978:8978'
    depends_on:
      db:
        condition: service_healthy
    environment:
      CB_SERVER_NAME: ${CB_SERVER_NAME}
      CB_ADMIN_NAME: ${CB_ADMIN_NAME}
      CB_ADMIN_PASSWORD: ${CB_ADMIN_PASSWORD}
    networks:
      - estadia_ja_network

  app:
    build: .
    container_name: node_app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - estadia_ja_network

  tester:
    build: .
    container_name: node_app_tester
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-test:5432/estadia_test_db
    depends_on:
      db-test:
        condition: service_healthy
    command: sh -c "npx prisma generate && npx prisma migrate deploy --schema=./prisma/schema.prisma && npm run test:all"
    networks:
      - estadia_ja_network

volumes:
  postgres_data:
  postgres_test_data:

networks:
  estadia_ja_network:
    external: true
